import { createHash } from 'node:crypto';
import { cp, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = fileURLToPath(new URL('../', import.meta.url));
const outputDir = path.resolve(process.argv[2] ?? path.join(projectRoot, 'dist'));
const publicDir = path.join(projectRoot, 'public');
const markerStart = '<!-- setline-pwa:start -->';
const markerEnd = '<!-- setline-pwa:end -->';
const workerFilename = 'service-worker.js';
const cachePrefix = 'setline-pwa-';

// Keep the exported HTML (with Expo's injected bundle) if a public template is
// added later. Recopy only the other public files, never a worker from a prior build.
await cp(publicDir, outputDir, {
  recursive: true,
  filter: (source) => !['index.html', workerFilename].includes(path.relative(publicDir, source)),
});
const indexPath = path.join(outputDir, 'index.html');
let html = await readFile(indexPath, 'utf8');
const oldMarkerStart = html.indexOf(markerStart);
if (oldMarkerStart !== -1) {
  const oldMarkerEnd = html.indexOf(markerEnd, oldMarkerStart);
  if (oldMarkerEnd === -1) throw new Error('The previous Setline PWA HTML block is incomplete.');
  html = html.slice(0, oldMarkerStart) + html.slice(oldMarkerEnd + markerEnd.length);
}
if (!html.includes('</head>')) throw new Error('The Expo export is missing an HTML head.');
const metadata = `${markerStart}
<link rel="manifest" href="/manifest.webmanifest" />
<link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<meta name="apple-mobile-web-app-title" content="Setline" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="theme-color" content="#2563eb" />
<script src="/register-sw.js" defer></script>
${markerEnd}`;
html = html.replace('</head>', `${metadata}</head>`);
await writeFile(indexPath, html);

async function listFiles(directory, relative = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const file = path.posix.join(relative, entry.name);
    if (entry.isDirectory()) files.push(...await listFiles(path.join(directory, entry.name), file));
    else if (entry.isFile() && file !== workerFilename && !file.endsWith('.map')) files.push(file);
    else if (entry.isSymbolicLink()) throw new Error(`Export contains an unexpected symbolic link: ${file}`);
  }
  return files.sort();
}

const files = await listFiles(outputDir);
const hash = createHash('sha256');
for (const file of files) {
  hash.update(file);
  hash.update('\0');
  hash.update(await readFile(path.join(outputDir, file)));
  hash.update('\0');
}
const version = hash.digest('hex').slice(0, 20);
const urls = files.map((file) => '/' + file.split('/').map(encodeURIComponent).join('/'));

const worker = `// Generated by scripts/finalize-web.mjs. Cache only this origin's app shell.
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(version)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      // addAll commits as one batch. Never activate a partially cached shell.
      await cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' })));
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.status < 500) return response;
      } catch {
        // A cached shell can explain the missing connection. It cannot cache the remote gym.
      }
      const cache = await caches.open(CACHE_NAME);
      return await cache.match('/index.html') || await cache.match('/offline.html') ||
        new Response('Setline needs an internet connection. Please reconnect and reload.', {
          status: 503,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    })());
    return;
  }

  if (PRECACHE_PATHS.has(url.pathname)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      return await cache.match(url.pathname) || fetch(request);
    })());
  }
});
`;
await writeFile(path.join(outputDir, workerFilename), worker);
console.log(`Finalized Setline PWA: ${files.length} shell files, cache ${cachePrefix}${version}.`);
