import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = fileURLToPath(new URL('../', import.meta.url));
const outputDir = path.resolve(process.argv[2] ?? path.join(projectRoot, 'dist'));
const workerFilename = 'service-worker.js';
const cachePrefix = 'setline-pwa-';

// Vite builds index.html and copies public/. Metadata belongs in the source HTML;
// this step only adds a worker derived from the finished, immutable build files.
await readFile(path.join(outputDir, 'index.html'));

async function listFiles(directory, relative = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const file = path.posix.join(relative, entry.name);
    if (entry.isDirectory()) files.push(...await listFiles(path.join(directory, entry.name), file));
    else if (entry.isFile() && file !== workerFilename && !file.endsWith('.map')) files.push(file);
    else if (entry.isSymbolicLink()) throw new Error(`Export contains an unexpected symbolic link: ${file}`);
  }
  return files.sort();
}

const files = await listFiles(outputDir);
const hash = createHash('sha256');
for (const file of files) {
  hash.update(file);
  hash.update('\0');
  hash.update(await readFile(path.join(outputDir, file)));
  hash.update('\0');
}
const version = hash.digest('hex').slice(0, 20);
const urls = files.map((file) => '/' + file.split('/').map(encodeURIComponent).join('/'));

const worker = `// Generated by scripts/finalize-web.mjs. Cache only this origin's app shell.
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(version)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      // addAll commits as one batch. Never activate a partially cached shell.
      await cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' })));
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Let an older open app finish using its existing asset version. The update
    // activates when those tabs close, so a session never loses its cached files.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.status < 500) return response;
      } catch {
        // The local bundle and persisted workout data remain usable offline.
      }
      const cache = await caches.open(CACHE_NAME);
      return await cache.match('/index.html') || await cache.match('/offline.html') ||
        new Response('Setline has not finished downloading. Reconnect once, then reopen the app.', {
          status: 503,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    })());
    return;
  }

  if (PRECACHE_PATHS.has(url.pathname)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      return await cache.match(url.pathname) || fetch(request);
    })());
  }
});
`;
await writeFile(path.join(outputDir, workerFilename), worker);
console.log(`Finalized Setline PWA: ${files.length} app files, cache ${cachePrefix}${version}.`);
